var quizLessonBoth = "lesson";var lessonNumber = 6;var numOfAllQuiz = 9;var lessonTitle = "Conectores básicos (Basic connection words II)";var quesToRemove = [];var titleSkip = [false,false,false,true];var startNarration = [];var narration = ["E = And","Ou = Or","Também = Also / Too / As well","","",""];var forExamples = ["Pablo <strong>e</strong> Carmen são amigos.","É acessível <strong>e</strong> de boa qualidade.","Tem ketchup <strong>e</strong> mostarda em seu cachorro-quente.","Tem maçãs <strong>e</strong> laranjas no cesto.","Tenho um gato <strong>e</strong> um cachorro.","Você quer ir ao cinema <strong>ou</strong> ao restaurante?","O que você vai comer, a maçã <strong>ou</strong> o bolo?","Você quer o relógio preto <strong>ou</strong> o branco?","Qual você prefere? O cinza <strong>ou</strong> o branco?","Ele <strong>também</strong> tem muito talento.","Ela <strong>também</strong> corre no parque com frequência.","Eu <strong>também</strong> te amo!","Ela <strong>também</strong> come frutas."];var engExamples = ["Pablo <em>and</em> Carmen are friends.","It's affordable <em>and</em> of good quality.","There is ketchup <em>and</em> mustard in his hot dog.","There are apples <em>and</em> oranges in the basket.","I have a cat <em>and</em> a dog.","Do you want to go to the movies <em>or</em> the restaurant?","What will you eat, the apple <em>or</em> the cake?","Do you want the black clock <em>or</em> the white one?","Which one do you prefer? The grey one <em>or</em> the white one?","He <em>also</em> has a lot of talent.","She <em>also</em> runs in the park often.","I love you <em>too</em>! (I too, love you)","She <em>also</em> eats fruit."];var forTitles = ["E","Ou","Também"];var forSideTitles = ["E","Ou","Também"];var engTitles = ["And","Or","Also / Too / As well"];var engSideTitles = ["And","Or","Also / Too / As well"];var exampleNums = [5,4,4];var btnColor = ["#1EEC00","#163F00","#90E700","#254800"];

var forExtra1 = ["Sim, eu toco violão <strong>e</strong> piano.","Eu li um livro <strong>e</strong> dormi muito.","Você pode aprender <strong>e</strong> se divertir!","Adoramos dançar <strong>e</strong> cantar.","Trabalho <strong>e</strong> depois descanso.","Tomei banho <strong>e</strong> logo me vesti.","Ele entrou <strong>e</strong> me deu uma caixa grande.","Nós temos água, suco de maçã, café <strong>e</strong> chá.","Comi um ovo <strong>e</strong> depois comi outro.","Gosto de ver você sorrir <strong>e</strong> se divertir.","O seu cachorro é preto <strong>e</strong> o meu é branco.","Ela cheirou a sopa <strong>e</strong> gostou do aroma.","Nós apagaremos tudo <strong>e</strong> começaremos de novo.","Menti para o meu pai <strong>e</strong> não sei o que fazer."];
var engExtra1 = ["Yes, I play guitar <em>and</em> piano.","I read a book <em>and</em> slept a lot.","You can learn <em>and</em> have fun!","We love to dance <em>and</em> sing.","I work <em>and</em> then I rest.","I took a shower <em>and</em> then I got dressed.","He entered <em>and</em> gave me a big box.","We have water, apple juice, coffee <em>and</em> tea.","I ate an egg <em>and</em> then I ate another one.","I like to see you smile <em>and</em> have fun.","Your dog is black <em>and</em> mine is white.","She smelled the soup <em>and</em> she liked the smell.","We will erase everything <em>and</em> start again.","I lied to my father <em>and</em> I don't know what to do."];
var imageExtra1 = ["../../convo/images/convo12A.jpg","../../convo/images/convo57B.jpg","../../convo/images/convo59B.jpg","../../verb/36/images/pic1.jpg","../../block/15/images/pic1.jpg","../../block/15/images/pic6.jpg","../../verb/43/images/pic3.jpg","../../convo/images/convo62A.jpg","../../block/15/images/pic2.jpg","../../verb/92/images/pic1.jpg","../../block/44/images/pic1.jpg","../../verb/91/images/pic3.jpg","../../verb/161/images/pic4.jpg","../../verb/65/images/pic3.jpg"];
var fastExtra1 = ["../../convo/12/sounds/1fast7","../../convo/57/sounds/2fast5","../../convo/59/sounds/2fast6","../../verb/36/sounds/sound3","../../block/15/sounds/sound1","../../block/15/sounds/sound11","../../verb/43/sounds/sound11","../../convo/62/sounds/1fast9","../../block/15/sounds/sound3","../../verb/92/sounds/sound3","../../block/44/sounds/sound1","../../verb/91/sounds/sound11","../../verb/161/sounds/sound15","../../verb/65/sounds/sound11"];
var slowExtra1 = ["../../convo/12/sounds/1slow7","../../convo/57/sounds/2slow5","../../convo/59/sounds/2slow6","../../verb/36/sounds/sound4","../../block/15/sounds/sound2","../../block/15/sounds/sound12","../../verb/43/sounds/sound12","../../convo/62/sounds/1slow9","../../block/15/sounds/sound4","../../verb/92/sounds/sound4","../../block/44/sounds/sound2","../../verb/91/sounds/sound12","../../verb/161/sounds/sound16","../../verb/65/sounds/sound12"];


var forExtra2 = ["Você tem irmãos <strong>ou</strong> irmãs?","Eu serei paga semanalmente <strong>ou</strong> mensalmente?","Esta é a sua opinião <strong>ou</strong> um fato?","Nós temos biscoito, pretzel <strong>ou</strong> amendoim.","Tu preferes ir à direita <strong>ou</strong> à esquerda?","Você prefere um assento no corredor <strong>ou</strong> na janela?","Que bom. A senhora gostaria de um café <strong>ou</strong> chá?","Claro. O senhor quer gasolina comum <strong>ou</strong> premium?","Eu gostaria de fazer compras <strong>ou</strong> assistir a um filme.","Você quer enviá-la pelo correio normal <strong>ou</strong> expresso?","Você se lembra se o assaltante era um homem <strong>ou</strong> uma mulher?"];
var engExtra2 = ["Do you have any brothers <em>or</em> sisters?","Will I be paid weekly <em>or</em> monthly?","Is that your opinion <em>or</em> a fact?","We have cookies, pretzels <em>or</em> peanuts.","Do you prefer going right <em>or</em> left?","Do you prefer an aisle <em>or</em> window seat?","Very good. Would you like a coffee <em>or</em> a tea?","Of course. Do you want regular <em>or</em> premium gas?","I would like to go shopping <em>or</em> watch a movie.","Do you want to send it by regular <em>or</em> express mail?","Do you remember if the robber was a man <em>or</em> a woman?"];
var imageExtra2 = ["../../convo/images/convo11A.jpg","../../convo/images/convo37B.jpg","../../vocab/89/images/pic2.jpg","../../convo/images/convo62A.jpg","../../verb/141/images/pic2.jpg","../../convo/images/convo30B.jpg","../../convo/images/convo10A.jpg","../../convo/images/convo48A.jpg","../../convo/images/convo55A.jpg","../../convo/images/convo18A.jpg","../../convo/images/convo51A.jpg"];
var fastExtra2 = ["../../convo/11/sounds/1fast1","../../convo/37/sounds/2fast7","../../vocab/89/sounds/sound7","../../convo/62/sounds/1fast13","../../verb/141/sounds/sound7","../../convo/30/sounds/2fast6","../../convo/10/sounds/1fast2","../../convo/48/sounds/1fast2","../../convo/55/sounds/1fast8","../../convo/18/sounds/1fast8","../../convo/51/sounds/1fast3"];
var slowExtra2 = ["../../convo/11/sounds/1slow1","../../convo/37/sounds/2slow7","../../vocab/89/sounds/sound8","../../convo/62/sounds/1slow13","../../verb/141/sounds/sound8","../../convo/30/sounds/2slow6","../../convo/10/sounds/1slow2","../../convo/48/sounds/1slow2","../../convo/55/sounds/1slow8","../../convo/18/sounds/1slow8","../../convo/51/sounds/1slow3"];


var forExtra3 = ["Você <strong>também</strong> pode ter náuseas.","Eu <strong>também</strong> estou aqui de férias.","Eu <strong>também</strong> quero um pouco de cuscuz.","Legal! Eu <strong>também</strong> quero ir para lá.","Ele <strong>também</strong> construiu esse banheirinho.","Eu <strong>também</strong> gostaria de enviar esta carta.","Sim. Eu <strong>também</strong> gostaria de uma televisão.","Só uma, mas eu <strong>também</strong> tenho bagagem de mão."];
var engExtra3 = ["You could <em>also</em> have nausea.","I am <em>also</em> here on vacation.","I will <em>also</em> take some couscous.","Great! I <em>also</em> want to go there.","He <em>also</em> built this small bathroom.","I would <em>also</em> like to send this letter.","Yes. I would <em>also</em> like a television.","Only one, but I <em>also</em> have hand luggage."];
var imageExtra3 = ["../../convo/images/convo21B.jpg","../../convo/images/convo64A.jpg","../../convo/images/convo9B.jpg","../../convo/images/convo56A.jpg","../../convo/images/convo42A.jpg","../../convo/images/convo18B.jpg","../../convo/images/convo6B.jpg","../../convo/images/convo30A.jpg"];
var fastExtra3 = ["../../convo/21/sounds/2fast10","../../convo/64/sounds/1fast7","../../convo/9/sounds/2fast4","../../convo/56/sounds/1fast11","../../convo/42/sounds/1fast9","../../convo/18/sounds/2fast3","../../convo/6/sounds/2fast5","../../convo/30/sounds/1fast6"];
var slowExtra3 = ["../../convo/21/sounds/2slow10","../../convo/64/sounds/1slow7","../../convo/9/sounds/2slow4","../../convo/56/sounds/1slow11","../../convo/42/sounds/1slow9","../../convo/18/sounds/2slow3","../../convo/6/sounds/2slow5","../../convo/30/sounds/1slow6"];