var quizLessonBoth = "lesson";var lessonNumber = 54;var numOfAllQuiz = 56;var lessonTitle = "Negações (Negations II)";var quesToRemove = [];var titleSkip = [false,false,false,true];var startNarration = [];var narration = ["Let's go through the most common and useful Portuguese negations.","","","","",""];var forExamples = ["<strong>Não</strong> estou feliz.","Ela <strong>não</strong> é uma bruxa de verdade.","Ela <strong>ainda não</strong> chegou.","Ele <strong>ainda não</strong> sabe.","Nós <strong>ainda não</strong> terminamos de pintar.","Ela <strong>não</strong> gosta <strong>nada</strong> de espinafre.","Ele <strong>não</strong> gosta <strong>nada</strong> de futebol.","Ela <strong>não</strong> gosta <strong>nada</strong> de iogurte."];var engExamples = ["I am <em>not</em> happy.","She is <em>not</em> a real witch.","She has <em>not</em> arrived <em>yet</em>.","He does <em>not</em> know <em>yet</em>.","We have <em>not</em> finished painting <em>yet</em>.","She does <em>not</em> like spinach <em>at all</em>.","He does <em>not</em> like soccer <em>at all</em>.","She does <em>not</em> like yogurt <em>at all</em>."];var forTitles = ["Não","Ainda não","Não… nada"];var forSideTitles = ["Não","Ainda não","Não… nada"];var engTitles = ["Not","Not... yet","Not... at all"];var engSideTitles = ["Not","Not... yet","Not... at all"];var exampleNums = [2,3,3];var btnColor = ["#1EEC00","#163F00","#90E700","#254800"];var forExtra2 = ["Não, <em>ainda</em><strong> não</strong>! Eu quero ir em breve!","Eu não falo. Bem, <em>ainda</em><strong> não</strong>. Eu estou aprendendo.","Como eu posso usar livros se eu <em>ainda</em><strong> não</strong> conheço o idioma?","Temos um quarto para esta noite. No entanto, ele <em>ainda</em><strong> não</strong> está pronto."];

var engExtra2 = ["No, <em>not yet</em>! I want to go soon!","I don't (speak). Well, <em>not yet</em>. I am learning.","How can I use books if I do <em>not</em> know the language <em>yet</em>?","We have a room for tonight. However, it is <em>not</em> ready <em>yet</em>."];
var imageExtra2 = ["../../convo/images/convo64B.jpg","../../convo/images/convo60B.jpg","../../convo/images/convo59A.jpg","../../block/86/images/pic4.jpg"];
var fastExtra2 = ["../../convo/64/sounds/2fast12","../../convo/60/sounds/2fast5","../../convo/59/sounds/1fast2","../../block/86/sounds/sound7"];
var slowExtra2 = ["../../convo/64/sounds/2slow12","../../convo/60/sounds/2slow5","../../convo/59/sounds/1slow2","../../block/86/sounds/sound8"];
var forExtra3 = ["Eu <em>não</em> estou me sentindo <strong>nada</strong> bem."];
var engExtra3 = ["I do <em>not</em> feel well <em>at</em><em> all</em>."];
var imageExtra3 = ["../../convo/images/convo20B.jpg"];
var fastExtra3 = ["../../convo/20/sounds/2fast1"];
var slowExtra3 = ["../../convo/20/sounds/2slow1"];