var lessonNumber = 21;var lessonTitle = "Ter que (To have to) - Future";var forExamples = ["(Eu) terei que","<strong>Terei que</strong> lavar as roupas esta tarde.","(Você) terá que","<strong>Você terá que</strong> limpar a cozinha.","(Ele) terá que","<strong>Ele terá que</strong> encontrar outra solução.","(Nós) teremos que","<strong>Teremos que</strong> abrir todas essas caixas.","(Vocês) terão que","<strong>Vocês terão que</strong> estudar para a prova.","(Eles) terão que","<strong>Eles terão que</strong> tomar conta do bebê."];var engExamples = ["I will have to","<em>I will have to</em> do the laundry this afternoon.","You will have to","<em>You will have to</em> clean the kitchen. (Brazil informal)","He will have to","<em>He will have to</em> find another solution.","We will have to","<em>We will have to</em> open all these boxes.","You will have to","<em>You will have to</em> study for the exam. (plural)","They will have to","<em>They will have to</em> take care of the baby."];var btnColor = ["#1EEC00","#163F00"];

var forConj1 = ["eu t<strong>enho</strong> que","tu t<strong>ens</strong> que","você t<strong>em</strong> que","ele/ela t<strong>em</strong> que","nós t<strong>emos</strong> que","vocês t<strong>êm</strong> que","eles/elas t<strong>êm</strong> que"];
var forConj2 = ["eu t<strong>ive</strong> que","tu t<strong>iveste</strong> que","você t<strong>eve</strong> que","ele/ela t<strong>eve</strong> que","nós t<strong>ivemos</strong> que","vocês t<strong>iveram</strong> que","eles/elas t<strong>iveram</strong> que"];
var forConj3 = ["eu t<strong>inha</strong> que","tu t<strong>inhas</strong> que","você t<strong>inha</strong> que","ele/ela t<strong>inha</strong> que","nós t<strong>ínhamos</strong> que","vocês t<strong>inham</strong> que","eles/elas t<strong>inham</strong> que"];
var forConj4 = ["eu t<strong>erei</strong> que","tu t<strong>erás</strong> que","você t<strong>erá</strong> que","ele/ela t<strong>erá</strong> que","nós t<strong>eremos</strong> que","vocês t<strong>erão</strong> que","eles/elas t<strong>erão</strong> que"];
var forConj5 = ["eu t<strong>eria</strong> que","tu t<strong>erias</strong> que","você t<strong>eria</strong> que","ele/ela t<strong>eria</strong> que","nós t<strong>eríamos</strong> que","vocês t<strong>eriam</strong> que","eles/elas t<strong>eriam</strong> que"];

var engConj1 = ["I have to","you have to (PT)","you have to (BR)","he/she/it has to","we have to","you have to (plural)","they have to"];var engConj2 = ["I had to","you had to (PT)","you had to (BR)","he/she/it had to","we had to","you had to (plural)","they had to"];var engConj3 = ["I was having to","you were having to (PT)","you were having to (BR)","he/she/it was having to","we were having to","you were having to (plural)","they were having to"];var engConj4 = ["I will have to","you will have to (PT)","you will have to (BR)","he/she/it will have to","we will have to","you will have to (plural)","they will have to"];var engConj5 = ["I would have to","you would have to (PT)","you would have to (BR)","he/she/it would have to","we would have to","you would have to (plural)","they would have to"];

var quizConj1 = ["tenho que","tens que","tem que","temos que","têm que","têm que"];
var quizConj2 = ["tive que","tiveste que","teve que","tivemos que","tiveram que","tiveram que"];
var quizConj3 = ["tinha que","tinhas que","tinha que","tínhamos que","tinham que","tinham que"];
var quizConj4 = ["terei que","terás que","terá que","teremos que","terão que","terão que"];
var quizConj5 = ["teria que","terias que","teria que","teríamos que","teriam que","teriam que"];

var verbTypeNum = 11;var forConj6 = "tendo que";var forConj7 = "t";var pronominal = false;var conjNum = [4,4,4,4,4,4,4,4,4,4,4,4];var irregReason = [""];var quizForExamples  = ["<strong>Nós teremos que</strong> atender muitas chamadas.","<strong>Eu terei que</strong> me deitar em breve.","<strong>Você terá que</strong> ensinar sua filha.","<strong>Ela terá que</strong> amarrar seus sapatos."];var quizEngExamples  = ["<em>We will have to</em> answer many calls.","<em>I will have to</em> go to bed soon.","<em>You will have to</em> teach your daughter. (Brazil informal)","<em>She will have to</em> tie her shoes."];