var quizLessonBoth = "lesson";var lessonNumber = 50;var numOfAllQuiz = 52;var lessonTitle = "Pronomes demonstrativos (Demonstrative pronouns I)";var quesToRemove = [];var titleSkip = [false,false,false,true];var startNarration = ["In the next few lessons, we will take a look at the equivalence of <strong>this</strong> and <strong>that</strong> in Portuguese.","Demonstrative pronouns are fairly complex in Portuguese. First, we will take a look at the <strong>neutral</strong> pronouns, meaning they are neither masculine nor feminine.","They are used when <strong>this</strong> or <strong>that</strong> do not replace a specific noun.","Let's take a look at the three different neutral demonstrative pronouns..."];var narration = ["","","","","",""];var forExamples = ["Sim, meu amigo me disse <strong>isto</strong>.","Quem fez <strong>isto</strong>?","Não vou esquecer <strong>isto</strong>.","Me dê <strong>isso</strong>!","<strong>Isso</strong> não é justo.","Não quero <strong>isso</strong>.","O que é <strong>aquilo</strong>?","Está vendo <strong>aquilo</strong>?"];var engExamples = ["Yes, my friend told me <em>this</em>.","Who did <em>this</em>?","I won't forget <em>this</em>.","Give me <em>that</em>!","<em>That</em> is not fair.","I don't want <em>that</em>.","What is <em>that over there</em>?","Do you see <em>that over there</em>?"];var forTitles = ["Isto","Isso","Aquilo"];var forSideTitles = ["Isto","Isso","Aquilo"];var engTitles = ["This","That","That (over there)"];var engSideTitles = ["This","That","That (over there)"];var exampleNums = [3,3,2];var btnColor = ["#1EEC00","#163F00","#90E700","#254800"];var forExtra1 = ["Observe <strong>isto</strong> atentamente.","Ficarei com <strong>isto</strong> para sempre.","Tenho que terminar <strong>isto</strong> para a próxima segunda-feira."];var engExtra1 = ["Observe <em>this</em> attentively.","I will keep <em>this</em> forever.","I have to finish <em>this</em> by next Monday."];var imageExtra1 = ["../../block/84/images/pic1.jpg","../../block/68/images/pic14.jpg","../../block/90/images/pic9.jpg"];var fastExtra1 = ["../../block/84/sounds/sound1","../../block/68/sounds/sound27","../../block/90/sounds/sound17"];var slowExtra1 = ["../../block/84/sounds/sound2","../../block/68/sounds/sound28","../../block/90/sounds/sound18"];

var forExtra2 = ["<strong>Isso</strong> não é chato?","<strong>Isso</strong> vai demorar?","<strong>Isso</strong> é impressionante!","<strong>Isso</strong> vai levar um tempo.","Como <strong>isso</strong> é possível?","Sério? <strong>Isso</strong> não é um pouco bobo?","Certo, eu vou fazer <strong>isso</strong> imediatamente.","Ah, eu não sabia que <strong>isso</strong> era necessário."];
var engExtra2 = ["Isn't <em>that</em> boring?","Will <em>that</em> take long?","<em>That</em> is very impressive!","<em>That</em> will take a while.","How is <em>that</em> possible?","Really? Isn't <em>that</em> a bit silly?","Okay, I'll do <em>that</em> right away.","Oh, I didn't know it needed <em>that</em>."];
var imageExtra2 = ["../../convo/images/convo57A.jpg","../../convo/images/convo47A.jpg","../../convo/images/convo42B.jpg","../../convo/images/convo59A.jpg","../../block/60/images/pic7.jpg","../../convo/images/convo60A.jpg","../../convo/images/convo20B.jpg","../../convo/images/convo47A.jpg"];
var fastExtra2 = ["../../convo/57/sounds/1fast6","../../convo/47/sounds/1fast12","../../convo/42/sounds/2fast8","../../convo/59/sounds/1fast9","../../block/60/sounds/sound13","../../convo/60/sounds/1fast4","../../convo/20/sounds/2fast12","../../convo/47/sounds/1fast11"];
var slowExtra2 = ["../../convo/57/sounds/1slow6","../../convo/47/sounds/1slow12","../../convo/42/sounds/2slow8","../../convo/59/sounds/1slow9","../../block/60/sounds/sound14","../../convo/60/sounds/1slow4","../../convo/20/sounds/2slow12","../../convo/47/sounds/1slow11"];


var forExtra3 = ["<strong>Aquilo</strong> é realmente necessário?","Entendi. <strong>Aquilo</strong> ainda não parece uma bola para mim."];var engExtra3 = ["Is <em>that</em> (<em>over there</em>) really necessary?","I see. <em>That</em> (<em>over there</em>) still doesn't look like a ball to me."];var imageExtra3 = ["../../vocab/89/images/pic6.jpg","../../convo/images/convo44A.jpg"];

var fastExtra3 = ["../../vocab/89/sounds/sound23","../../convo/44/sounds/1fast11"];var slowExtra3 = ["../../vocab/89/sounds/sound24","../../convo/44/sounds/1slow11"];