var quizLessonBoth = "lesson";var lessonNumber = 32;var numOfAllQuiz = 34;var lessonTitle = "Pronomes preposicionais (Prepositional Pronouns II)";var quesToRemove = [];var titleSkip = [false,false,false,true];var startNarration = [];var narration = ["","","","","",""];var forExamples = ["Quer tirar uma foto d<strong>a gente</strong>? (de + a = da)","Tem algo embaixo de <strong>nós</strong>.","Você quer cantar para <strong>nós</strong>?","Não posso terminar o trabalho sem <strong>vocês</strong>.","Quero consertar o carro com <strong>vocês</strong>.","Estou preparando o jantar para <strong>vocês</strong>.","Tenho fé em <strong>vocês</strong>.","Sempre falo com <strong>elas</strong>.","Gosto muito de correr com <strong>eles</strong>.","O lago está em frente a <strong>eles</strong>.","Gosto de sair com <strong>elas</strong>."];var engExamples = ["Do you want to take a picture of <em>us</em>? (the people)","There is something below <em>us</em>.","Do you want to sing for <em>us</em>?","I can't finish the work without <em>you</em>. (plural)","I want to fix the car with <em>you</em>. (plural)","I am making dinner for <em>you</em>. (plural)","I have faith in <em>you</em>. (plural)","I always talk with <em>them</em>. (feminine)","I really like to run with <em>them</em>. (masculine)","The lake is in front of <em>them</em>. (masculine)","I like going out with <em>them</em>. (feminine)"];var forTitles = ["Nós / A gente","Vocês","Eles / Elas"];var forSideTitles = ["Nós<br>A gente","Vocês","Eles<br>Elas"];var engTitles = ["Us","You (plural)","Them"];var engSideTitles = ["Us","You (plural)","Them"];var exampleNums = [3,4,4];var btnColor = ["#1EEC00","#163F00","#90E700","#254800"];


var forExtra1 = ["Um estranho entre <strong>nós</strong>.","Como você ficou sabendo d<strong>a gente</strong>?"];
var engExtra1 = ["A stranger among <em>us</em>.","How did you learn about <em>us</em>?"];
var imageExtra1 = ["../../block/17/images/pic9.jpg","../../convo/images/convo37A.jpg"];
var fastExtra1 = ["../../block/17/sounds/sound17","../../convo/37/sounds/1fast2"];
var slowExtra1 = ["../../block/17/sounds/sound18","../../convo/37/sounds/1slow2"];

var forExtra2 = ["Eu poderia ir com <strong>vocês</strong>.","Se minha perna não estivesse quebrada, eu correria com <strong>vocês</strong>."];
var engExtra2 = ["I could go with <em>you</em>. <i class='qhint'>(plural)</i>","If my leg weren't broken, I would run with <em>you</em>. <i class='qhint'>(plural)</i>"];
var imageExtra2 = ["../../verb/18/images/pic4.jpg","../../verb/84/images/pic6.jpg"];
var fastExtra2 = ["../../verb/18/sounds/sound15","../../verb/84/sounds/sound23"];
var slowExtra2 = ["../../verb/18/sounds/sound16","../../verb/84/sounds/sound24"];

var forExtra3 = ["Sim, nós temos muitos d<strong>eles</strong>.","Então, como eu posso aprender com <strong>eles</strong>?","Sim. Nós temos muitos d<strong>eles</strong> em estoque.","O senhor quer fazer negócios com <strong>eles</strong>.","As crianças ficaram correndo atrás d<strong>eles</strong>. Foi hilário.","Eles são gratos que tu cozinhes o jantar para <strong>eles</strong>.","Se não fosse tão tímido, ele falaria com <strong>elas</strong>."];
var engExtra3 = ["Yes, we have many of <em>them</em>. <i class='qhint'>(masculine)</i>","So, how can I learn with <em>them</em>? <i class='qhint'>(masculine)</i>","Yes. We have many of <em>them</em> in stock. <i class='qhint'>(masculine)</i>","You want to do business with <em>them</em>. <i class='qhint'>(masculine)</i>","The kids were chasing after <em>them</em>. It was hilarious. <i class='qhint'>(masculine)</i>","They are grateful that you cook dinner for <em>them</em>. <i class='qhint'>(masculine)</i>","If he weren't shy, he would talk to <em>them</em>. <i class='qhint'>(feminine)</i>"];
var imageExtra3 = ["../../convo/images/convo25A.jpg","../../convo/images/convo59A.jpg","../../convo/images/convo33A.jpg","../../verb/13/images/pic6.jpg","../../convo/images/convo55B.jpg","../../verb/152/images/pic2.jpg","../../verb/99/images/pic6.jpg"];
var fastExtra3 = ["../../convo/25/sounds/1fast5","../../convo/59/sounds/1fast7","../../convo/33/sounds/1fast6","../../verb/13/sounds/sound23","../../convo/55/sounds/2fast4","../../verb/152/sounds/sound7","../../verb/99/sounds/sound23"];
var slowExtra3 = ["../../convo/25/sounds/1slow5","../../convo/59/sounds/1slow7","../../convo/33/sounds/1slow6","../../verb/13/sounds/sound24","../../convo/55/sounds/2slow4","../../verb/152/sounds/sound8","../../verb/99/sounds/sound24"];